name: run main.py

on:
  schedule:
    - cron: '*/2 * * * *' # At 00:00 on Monday

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: checkout repo content
        uses: actions/checkout@v3   # checkout the repository content to github runner

      - name: setup python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10' # install the python version needed
          
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: execute py script # run main.py
        env:
          SOME_SECRET: ${{ secrets.SOME_SECRET }}
        run: python main.py
          
      - name: commit files
        run: |
          git config --local user.email "daniel0422@gmail.com"
          git config --local user.name "DanielChou"
          git add -A
          git diff-index --quiet HEAD || (git commit -a -m "updated logs" --allow-empty)
          git pull origin master
          git push
          
      # - name: push changes
      #   uses: ad-m/github-push-action@v0.6.0
      #   with:
      #     github_token: ${{ secrets.DANIEL_TOKEN }}
      #     branch: main 
